export const actions = {
  POST_CHANGE_SHOPDETAIL: "POST_CHANGE_SHOPDETAIL",
  POST_INITIAL_SHOPDETAIL: "POST_INITIAL_SHOPDETAIL",
  POST_SHOPID: "POST_SHOPID",
  RESET_SHOPID: "RESET_SHOPID",
  POST_NEWSHOP: "POST_NEWSHOP",

  CHANGE_CURRENT_CATEGORY: "CHANGE_CURRENT_CATEGORY"
};
