export const actions = {
  POST_CHANGE_SHOPDETAIL: "POST_CHANGE_SHOPDETAIL",
  POST_INITIAL_SHOPDETAIL: "POST_INITIAL_SHOPDETAIL",
  POST_SHOPID: "POST_SHOPID",
  RESET_SHOPID: "RESET_SHOPID",

  CHANGE_LOGIN_STATE: "CHANGE_LOGIN_STATE",
  CHANGE_CURRENT_CATEGORY: "CHANGE_CURRENT_CATEGORY",
  CHANGE_CAN_REGISTER_STATE: "CHANGE_CAN_REGISTER_STATE",
  OPEN_ADD_SHOP_MODAL: "OPEN_ADD_SHOP_MODAL",
  OPEN_ADD_CATEGORY_MODAL: "OPEN_ADD_CATEGORY_MODAL"
};
